---
title: How bad are fiscal revisions in the euro area?
author:
  - name: Krzysztof Bankowski
    email: krzysztof.bankowski@europa.ecb.eu
    affiliations: 
        - id: ECB
          name: European Central Bank
          department: Fiscal Policies Division
          # address:  Sonnemannstrasse 20
          city: Frankfurt
          postal-code: 60314
    # attributes:
    #     corresponding: true
    # note: This is the first author footnote.
  - name: Thomas Faria
    email: thomas.faria@insee.fr
    affiliations:
        - id: Insee
          name: Institut national de la statistique et des études économiques
          department: SSP Lab
          # address: 88, avenue Verdier
          city: Montrouge
          postal-code: 92541
  - name: Robert Schall
    email: robert.schall@eui.eu
    affiliations:
        - id: EUI
          name: European University Institute
          city: Fiesole
          postal-code: 50014

abstract: |
  We investigate the properties of fiscal revisions in the euro area by contrasting them with macro revisions. To this end, we construct a fiscal real-time dataset containing quarterly releases of Government Finance Statistics, which is supplemented by macro variables from Main National Accounts. Fiscal revisions, like macro revisions, do not satisfy desirable properties expected from well-behaved revisions. In particular, they tend to have positive mean, are non-negligible in size and are predictable. With our investigation we contradict the often heard view that fiscal data are subject to extraordinarily sizeable revisions. While it was the case some years ago since 2014 the revisions for the main fiscal categories are in the same ballpark as the revisions for the main macroeconomic series. In general, properties of fiscal and macro revisions are quite similar since the introduction of ESA 2010 in 2014.
keywords: 
  - Fiscal policy
  - real-time data
  - data revisions
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    keep-tex: false
    journal:
      name: International Journal of Central Banking
      formatting: preprint
      model: 3p
      cite-style: authoryear
    toc: true
    include-in-header:
      - packages.tex
    # lof: true
    # lot: true
---

\newpage{}

# Introduction
{{< include sections/1-Introduction.qmd >}}

# Real-time quarterly fiscal dataset {#sec-Real-time-quarterly-fiscal}
{{< include sections/2-Data.qmd >}}

# Unconditional properties of final revisions {#sec-Magnitude-of-total}
{{< include sections/3-Uncond-properties.qmd >}}

# Predictability final revisions {#sec-Predictability}
{{< include sections/4-Predictability.qmd >}}

# Properties of intermediate revisions {#sec-Intermediate-revisions}
{{< include sections/5-Intermediate-revisions.qmd >}}

# Conclusions {#sec-Conclusions}
{{< include sections/6-Conclusion.qmd >}}

\newpage{}

Please make sure that your manuscript follows the guidelines in the 
Guide for Authors of the relevant journal. It is not necessary to 
typeset your manuscript in exactly the same way as an article, 
unless you are submitting to a camera-ready copy (CRC) journal.

For detailed instructions regarding the elsevier article class, see   <https://www.elsevier.com/authors/policies-and-guidelines/latex-instructions>

# Bibliography styles

Here are two sample references:  @Feynman1963118 @Dirac1953888.

By default, natbib will be used with the `authoryear` style, set in `classoption` variable in YAML. 
You can sets extra options with `natbiboptions` variable in YAML header. Example 

```
natbiboptions: longnamesfirst,angle,semicolon
```

There are various more specific bibliography styles available at
<https://support.stmdocs.in/wiki/index.php?title=Model-wise_bibliographic_style_files>. 
To use one of these, add it in the header using, for example, `biblio-style: model1-num-names`.

## Using CSL 

If `cite-method` is set to `citeproc` in `elsevier_article()`, then pandoc is used for citations instead of `natbib`. In this case, the `csl` option is used to format the references. By default, this template will provide an appropriate style, but alternative `csl` files are available from <https://www.zotero.org/styles?q=elsevier>. These can be downloaded
and stored locally, or the url can be used as in the example header.

# References {-}
