# Complementing results {#sec-complementing-results}

::: {.content-visible when-format="pdf"}
\floatplacement{table}{!htbp}
:::

```{r}
#| label: tbl-forecastability_SIC
#| tbl-cap: Predictability of the revisions based on SIC
#| tbl-width: 8
#| tbl-height: 4.75

table <- targets::tar_read(table_BIC)

if (knitr::is_html_output()){
    table <- table|>
    dplyr::mutate_all(stringr::str_replace_all, pattern=stringr::fixed("$$"), replacement="")|>
    dplyr::mutate_all(stringr::str_replace_all, pattern=stringr::fixed("\\mathds{1}"), replacement="1")

kableExtra::kbl(table,
              col.names = c("",
                           "Expl. variable",
                           "N",
                           "F-value",
                           "Compl/Naive",
                           "Intrm1/Naive",
                           "Intrm2/Naive",
                           "Intrm3/Naive",
                           "Intrm4/Naive"),
              "markdown",
              escape = FALSE,
              booktabs = TRUE) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

} else {
    kableExtra::kbl(table,
                col.names = c("",
                            "Expl. variable",
                            "N",
                            "F-value",
                            "Compl/Naive",
                            "Intrm1/Naive",
                            "Intrm2/Naive",
                            "Intrm3/Naive",
                            "Intrm4/Naive"),
                escape = FALSE,
                booktabs = TRUE) |>
    kableExtra::pack_rows("Revenue", 1, 4) |>
    kableExtra::pack_rows("Expenditure", 5, 9) |>
    kableExtra::pack_rows("Macro", 10, 15) |>
    kableExtra::footnote(general = "$R_{t-i,m}$ in the specification of explanatory variables are past revisions defined by $R_{t-i,m}=\\\\left(x_{t-i,m}^{i+1}-x_{t-i,m}^{1}\\\\right)$, as introduced in the equation of the complete model.", escape=FALSE) |>
    kableExtra::kable_styling(latex_options = c("striped", "scale_down"))
}
```


```{r}
#| label: fig-Single-Rev-Path-pre2014
#| fig-cap: Revision paths across variables in the pre-2014Q2 subsample
#| fig-width: 6.3
#| fig-height: 5.75
#| fig-align: center

targets::tar_read(plot_revision_paths_pre2014)
```

```{r}
#| label: fig-Single-Rev-Path-post2014
#| fig-cap: Revision paths across variables in the post-2014Q2 subsample
#| fig-width: 6.3
#| fig-height: 5.75
#| fig-align: center

targets::tar_read(plot_revision_paths_post2014)
```
