# Data codes for retrieval {#sec-code-retrieval}
```{r}
#| label: tbl-Code-series-fiscal
#| tbl-cap: ECB's SDW codes for data retrieval (fiscal series)
 
text_tbl <- data.frame(
  Name = c(
    "Total revenue", 
    "Current taxes on income, wealth, etc. (Direct taxes)", 
    "Taxes on production and imports (Indirect taxes)", 
    "Net social contributions (Social contributions)", 
    "Other current revenue = Market output, output for own final use and payments for other non-market output + Other subsidies on production + Property income + Other current transfers", 
    "Capital transfers (Capital revenue)",
    "Total expenditure",
    "Social benefits other than social transfers in kind (Social transfers)",
    "Purchases = Social transfers in kind - purchased market production + Intermediate consumption",
    "Interest (Interest payments)",
    "Compensation of employees (Gov. compensation)",
    "Other current expenditure = Property income other than interest + Other taxes on production + Current taxes on income, wealth, etc. + Other current transfers + Adjustment for the change in pension entitlements",
    "Gross fixed capital formation (Gov. investment)",
    "Other capital expenditure = Changes in inventories and acquisition less disposals of valuables + Acquisitions less disposals of non-produced assets + Capital transfers"
    ),
  `Code` = c(
    "GFS.Q.N.*.W0.S13.S1.P.C.OTR._Z._Z._Z.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.C.D5._Z._Z._Z.XDC._Z.S.V.N._T", 
    "GFS.Q.N.*.W0.S13.S1.N.C.D2._Z._Z._Z.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.C.D61._Z._Z._Z.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.C.P1O._Z._Z._Z.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.C.D39._Z._Z._Z.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.P.C.D4._Z._Z._Z.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.P.C.D7._Z._Z._Z.XDC._Z.S.V.N._T", 
    "GFS.Q.N.*.W0.S13.S1.P.C.D9._Z._Z._Z.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.P.D.OTE._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D62._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D632._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.D.P2._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.C.D.D41._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D1._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D4N._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.D.D29._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.D.D5._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.P.D.D7._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.D.D8._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.P51G._Z._Z._T.XDC._Z.S.V.N._T",
    "GFS.Q.N.*.W0.S13.S1.N.D.P5M._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.N.D.NP._Z._Z._T.XDC._Z.S.V.N._T +
        GFS.Q.N.*.W0.S13.S1.C.D.D9._Z._Z._T.XDC._Z.S.V.N._T"
  )
)

if (knitr::is_html_output()){
  kableExtra::kbl(text_tbl, col.names = c("Name", "Retrieval code")) |>
    kableExtra::row_spec(c(5, 6, 10, 12, 14), bold = T, color = "#b4824b") |>
    kableExtra::footnote(general = " The items in brown are not explicitly considered in our analysis.", 
                            footnote_as_chunk = T) |>
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

} else {

  text_tbl <- data.frame(
  Name = c(
    "\\textbf{Total revenue}", 
    "Current taxes on income, wealth, etc. (\\textbf{Direct taxes})", 
    "Taxes on production and imports (\\textbf{Indirect taxes})", 
    "Net social contributions (\\textbf{Social contributions})", 
    "\\textbf{Other current revenue} = Market output, output for own final use and payments for other non-market output + Other subsidies on production + Property income + Other current transfers", 
    "Capital transfers (\\textbf{Capital revenue})",
    "\\textbf{Total expenditure}",
    "Social benefits other than social transfers in kind (\\textbf{Social transfers})",
    "\\textbf{Purchases} = Social transfers in kind - purchased market production + Intermediate consumption",
    "Interest (\\textbf{Interest payments})",
    "Compensation of employees (\\textbf{Gov. compensation})",
    "\\textbf{Other current expenditure} = Property income other than interest + Other taxes on production + Current taxes on income, wealth, etc. + Other current transfers + Adjustment for the change in pension entitlements",
    "Gross fixed capital formation (\\textbf{Gov. investment})",
    "\\textbf{Other capital expenditure} = Changes in inventories and acquisition less disposals of valuables + Acquisitions less disposals of non-produced assets + Capital transfers"
    ),
  `Code` = c(
    "GFS.Q.N.*.W0.S13.S1.P.C.OTR.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.C.D5.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T", 
    "GFS.Q.N.*.W0.S13.S1.N.C.D2.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.C.D61.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.C.P1O.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.C.D39.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.P.C.D4.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.P.C.D7.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T\n\n", 
    "GFS.Q.N.*.W0.S13.S1.P.C.D9.\\_Z.\\_Z.\\_Z.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.P.D.OTE.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D62.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D632.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.D.P2.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.C.D.D41.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D1.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.D.D4N.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.D.D29.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.D.D5.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.P.D.D7.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.D.D8.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T\n",
    "GFS.Q.N.*.W0.S13.S1.N.D.P51G.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T",
    "GFS.Q.N.*.W0.S13.S1.N.D.P5M.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.N.D.NP.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T +
        GFS.Q.N.*.W0.S13.S1.C.D.D9.\\_Z.\\_Z.\\_T.XDC.\\_Z.S.V.N.\\_T\n\n"
  )
)

text_tbl$Name <- kableExtra::linebreak(text_tbl$Name)
text_tbl$Code <- kableExtra::linebreak(text_tbl$Code)

  kableExtra::kbl(text_tbl, 
                  col.names = c("Name", "Retrieval code"),
                  escape = F,
                  booktabs = TRUE,
                  align = rep('c', 2)) |>
      kableExtra::pack_rows("Revenue", 1, 6) |>
      kableExtra::pack_rows("Expenditure", 7, 14) |>
      kableExtra::column_spec(1, width = "8cm") |>
      kableExtra::row_spec(c(5, 6, 10, 12, 14), bold = T, color = "#b4824b") |>
      kableExtra::footnote(general = " The items in brown are not explicitly considered in our analysis.") |>
      kableExtra::kable_styling(latex_options = c("striped", "scale_down"))

}

```
 
```{r}
#| label: tbl-Code-series-macro
#| tbl-cap: ECB's SDW codes for data retrieval (macro series)

if (knitr::is_html_output()){

text_tbl <- data.frame(
  Name = c("GDP", "Private consumption", "Total investment", "Exports", "Gov. consumption", "Compensation of employees"),
  `Code` = c(
    "MNA.Q.N.*.W2.S1.S1.B.B1GQ._Z._Z._Z.EUR.V.N",
    "MNA.Q.N.*.W0.S1M.S1.D.P31._Z._Z._T.EUR.V.N", 
    "MNA.Q.N.*.W0.S1.S1.D.P5.N1G._T._Z.EUR.V.N",
    "MNA.Q.N.*.W1.S1.S1.D.P6._Z._Z._Z.EUR.V.N",
    "MNA.Q.N.*.W0.S13.S1.D.P3._Z._Z._T.EUR.V.N", 
    "MNA.Q.N.*.W2.S1.S1.D.D1._Z._T._Z.EUR.V.N"
  )
)

kableExtra::kbl(text_tbl, col.names = c("Name", "Retrieval code")) |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

} else {

  text_tbl <- data.frame(
    Name = c("GDP", "Private consumption", "Total investment", "Exports", "Gov. consumption", "Compensation of employees"),
    `Code` = c(
      "MNA.Q.N.*.W2.S1.S1.B.B1GQ.\\_Z.\\_Z.\\_Z.EUR.V.N",
      "MNA.Q.N.*.W0.S1M.S1.D.P31.\\_Z.\\_Z.\\_T.EUR.V.N", 
      "MNA.Q.N.*.W0.S1.S1.D.P5.N1G.\\_T.\\_Z.EUR.V.N",
      "MNA.Q.N.*.W1.S1.S1.D.P6.\\_Z.\\_Z.\\_Z.EUR.V.N",
      "MNA.Q.N.*.W0.S13.S1.D.P3.\\_Z.\\_Z.\\_T.EUR.V.N", 
      "MNA.Q.N.*.W2.S1.S1.D.D1.\\_Z.\\_T.\\_Z.EUR.V.N"
    )
  )

text_tbl$Name <- kableExtra::linebreak(text_tbl$Name)
text_tbl$Code <- kableExtra::linebreak(text_tbl$Code)

  kableExtra::kbl(text_tbl, 
                  col.names = c("Name", "Retrieval code"),
                  escape = F,
                  booktabs = TRUE,
                  align = rep('c', 2)) |>
      kableExtra::kable_styling(latex_options = c("striped", "scale_down"))

}
```
