on:
  workflow_dispatch:
  push:
    branches: 4-implement-target-pipelines

name: Quarto Publish

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: thomasfaria/quarterly_gfs_revisions:latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Generate data
        run: |
          source("run.R")
        shell: Rscript {0} 

      # - name: Set up Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2

      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: '4.2.1'

      # - name: Install libcurl4
      #   run:  sudo apt install libcurl4-openssl-dev

      # - name: Install R Dependencies
      #   uses: r-lib/actions/setup-renv@v2
      #   with:
      #     cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: article/article.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
